{{ if .Values.database.cloudsql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: infrabox-cloudsql-instance-credentials
  namespace: {{ template "system_namespace" . }}
type: Opaque
data:
  credentials.json: |-
    {{ .Files.Get .Values.database.cloudsql.service_account_file | b64enc }}
{{ end }}
