{{ if .Values.storage.gcs.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: infrabox-gcs
  namespace: {{ template "system_namespace" . }}
type: Opaque
data:
  gcs_service_account.json: |-
    {{ .Files.Get .Values.storage.gcs.service_account_file | b64enc }}
{{ end }}
