{{ if .Values.gerrit.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: infrabox-gerrit-ssh
  namespace: {{ template "system_namespace" . }}
type: Opaque
data:
  id_rsa: |-
    {{ .Files.Get .Values.gerrit.private_key_file | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: infrabox-gerrit-ssh
  namespace: {{ template "worker_namespace" . }}
type: Opaque
data:
  id_rsa: |-
    {{ .Files.Get .Values.gerrit.private_key_file | b64enc }}
{{ end }}
