apiVersion: v1
kind: Secret
metadata:
  name: infrabox-rsa
  namespace: {{ template "system_namespace" . }}
type: Opaque
data:
  id_rsa: |-
    {{ .Files.Get (required "admin.private_key_file is required" .Values.admin.private_key_file) | b64enc }}
  id_rsa.pub: |-
    {{ .Files.Get (required "admin.public_key_file is required" .Values.admin.public_key_file) | b64enc }}
