apiVersion: v1
kind: Secret
metadata:
  name: infrabox-rsa
  namespace: {{ template "system_namespace" . }}
type: Opaque
data:
  id_rsa: |-
    {{ .Files.Get .Values.admin.private_key_file | b64enc }}
  id_rsa.pub: |-
    {{ .Files.Get .Values.admin.public_key_file | b64enc }}
