{{ if .Values.storage.s3.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: infrabox-s3-credentials
  namespace: {{ template "system_namespace" . }}
type: Opaque
data:
  username: {{ required "storage.swift.username is required" .Values.storage.swift.username | b64enc }}
  password: {{ required "storage.swift.password is required" .Values.storage.swift.password | b64enc }}
{{ end }}
