{{ if .Values.stats.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: infrabox-stats
    namespace: {{ default "infrabox-system" .Values.general.system_namespace }}
    labels:
        app: infrabox
        infrabox.net/component: stats
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: infrabox
                infrabox.net/component: stats
        spec:
            {{- if .Values.stats.node_selector }}
            nodeSelector:
{{ toYaml .Values.stats.node_selector | indent 16 }}
            {{- end }}
            containers:
            {{ include "containers_database" . | indent 12 }}
            -
                name: stats
                image: {{ .Values.general.docker_registry }}/{{ default "infrabox/stats" .Values.stats.image }}:{{ .Values.stats.tag }}
                imagePullPolicy: Always
                command:
                - "python"
                - "/stats/stats.py"
                volumeMounts:
                {{ if .Values.storage.gcs.enabled }}
                -
                    name: gcs-service-account
                    mountPath: /etc/infrabox/gcs
                    readOnly: true
                {{ end }}
                env:
                {{ include "env_database" . | indent 16 }}
                {{ include "env_kubernetes" . | indent 16 }}
                -
                    name: INFRABOX_SERVICE
                    value: {{ default "infrabox/stats" .Values.stats.image }}
                -
                    name: INFRABOX_VERSION
                    value: {{ .Values.stats.tag }}
                -
                    name: INFRABOX_STATS_KUBERNETES_ENABLED
                    value: "true"
            volumes:
                {{ include "volumes_database" . | indent 16 }}
                {{ if .Values.storage.gcs.enabled }}
                -
                    name: gcs-service-account
                    secret:
                        secretName: infrabox-gcs
                {{ end }}
{{ end }}
