{{ if .Values.scheduler.enabled }}

{{ if .Values.general.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infrabox-scheduler
  namespace: {{ default "infrabox-system" .Values.general.system_namespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: infrabox-scheduler
  namespace: {{ default "infrabox-system" .Values.general.system_namespace }}
subjects:
- kind: ServiceAccount
  name: infrabox-scheduler
  namespace: {{ default "infrabox-system" .Values.general.system_namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
{{ end }}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: infrabox-scheduler
    namespace: {{ default "infrabox-system" .Values.general.system_namespace }}
    labels:
        app: infrabox-scheduler
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: infrabox-scheduler
        spec:
            {{ if .Values.general.rbac.enabled }}
            serviceAccountName: infrabox-scheduler
            {{ end }}
            {{- if .Values.scheduler.node_selector }}
            nodeSelector:
{{ toYaml .Values.scheduler.node_selector | indent 16 }}
            {{- end }}
            containers:
            {{ include "containers_database" . | indent 12 }}
            -
                name: scheduler
                image: {{ required "general.docker_registry is required" .Values.general.docker_registry }}/{{ default "scheduler-kubernetes" .Values.scheduler.image }}:{{ required "scheduler.tag is required" .Values.scheduler.tag }}
                args:
                    - "--docker-registry"
                    - "{{ .Values.general.docker_registry }}"
                    - "--tag"
                    - "{{ .Values.scheduler.tag }}"
                imagePullPolicy: Always
                env:
                {{ include "env_database" . | indent 16 }}
                {{ include "env_gerrit" . | indent 16 }}
                {{ include "env_local_cache" . | indent 16 }}
                {{ include "env_job" . | indent 16 }}
                {{ include "env_general" . | indent 16 }}
                {{ include "env_kubernetes" . | indent 16 }}
                {{ include "env_job_api_secret" . | indent 16 }}
                -
                    name: INFRABOX_DASHBOARD_URL
                    value: {{ required "dashboard.url is required" .Values.dashboard.url }}
                -
                    name: INFRABOX_DOCKER_REGISTRY_URL
                    value: {{ required "docker_registry.url is required" .Values.docker_registry.url }}
                -
                    name: INFRABOX_SERVICE
                    value: {{ default "scheduler" .Values.scheduler.image }}
                -
                    name: INFRABOX_VERSION
                    value: {{ required "scheduler.tag is required" .Values.scheduler.tag }}
                -
                    name: INFRABOX_SCHEDULER_LOG_LEVEL
                    value: {{ default "info" .Values.scheduler.log.level }}
                -
                    name: INFRABOX_JOB_API_URL
                    value: {{ default .Values.job.api.url }}
                ports:
                - containerPort: 8000
                  name: prometheus
                volumeMounts:
                -
                    mountPath: /etc/docker
                    name: dockerd-config
            volumes:
                {{ include "volumes_database" . | indent 16 }}
                -
                    name: dockerd-config
                    configMap:
                        name: infrabox-dockerd-config
{{ end }}
