kind: Service
apiVersion: v1
metadata:
    name: infrabox-scheduler
    namespace: {{ default "infrabox-system" .Values.general.system_namespace }}
    labels:
        app: infrabox
        infrabox.net/component: scheduler
spec:
    selector:
        app: infrabox
        infrabox.net/component: scheduler
    ports:
    -
        name: monitoring
        protocol: TCP
        port: 8000
        targetPort: 8000
