{{ if .Values.github.enabled }}
kind: Service
apiVersion: v1
metadata:
    name: infrabox-github-trigger
    namespace: {{ default "infrabox-system" .Values.general.system_namespace }}
    labels:
        app: infrabox-github-trigger
spec:
    selector:
        app: infrabox-github-trigger
    ports:
    -
        name: http-web
        protocol: TCP
        port: 8080
        targetPort: 8080
{{ end }}
