apiVersion: v1
kind: ConfigMap
metadata:
  name: infrabox-dockerd-config
  namespace: {{ template "worker_namespace" . }}
data:
  daemon.json: |-
      {{ required "job.docker_daemon_config is required" .Values.job.docker_daemon_config }}
