{{ if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: infrabox
    namespace: infrabox-system
    annotations:
        {{- if .Values.ingress.annotations }}
        {{ toYaml .Values.ingress.annotations | indent 8 }}
        {{- end }}
spec:
    rules:
    -
        {{- if .Values.ingress.host }}
        host: {{ .Values.ingress.host }}
        {{- end }}
        http:
            paths:
            -
                path: /docs
                backend:
                    serviceName: infrabox-static
                    servicePort: 80
            -
                path: /dashboard
                backend:
                    serviceName: infrabox-static
                    servicePort: 80
            -
                path: /api/dashboard
                backend:
                    serviceName: infrabox-dashboard-api
                    servicePort: 8080
            -
                path: /api/cli
                backend:
                    serviceName: infrabox-api
                    servicePort: 8080
            -
                path: /api/job
                backend:
                    serviceName: infrabox-job-api
                    servicePort: 8080
            {{ if .Values.github.enabled }}
            -
                path: /github/hook
                backend:
                    serviceName: infrabox-github-trigger
                    servicePort: 8080
            -
                path: /github/auth
                backend:
                    serviceName: infrabox-dashboard-api
                    servicePort: 8080
            {{ end }}
            -
                path: /live/dashboard
                backend:
                    serviceName: infrabox-dashboard-api
                    servicePort: 8080
            -
                path: /v2
                backend:
                    serviceName: infrabox-docker-registry
                    servicePort: 8080
            -
                path: /
                backend:
                    serviceName: infrabox-static
                    servicePort: 80
    {{- if .Values.ingress.tls }}
    tls:
        {{- if .Values.ingress.annotations }}
        {{ toYaml .Values.ingress.tls | indent 8 }}
        {{- end }}
    {{- end }}
{{ end }}
