{{ if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: infrabox
    namespace: {{ default "infrabox-system" .Values.general.system_namespace }}
    annotations:
        kubernetes.io/ingress.class: "nginx"
        ingress.kubernetes.io/force-ssl-redirect: {{ .Values.ingress.tls.force_redirect | quote }}
        {{ if .Values.ingress.tls.enabled }}
        {{- if .Values.ingress.tls.acme }}
        kubernetes.io/tls-acme: "true"
        {{- end }}
        {{- end }}
spec:
    rules:
    -
        {{ if .Values.ingress.tls.enabled }}
        host: {{ .Values.ingress.tls.host }}
        {{ end }}
        http:
            paths:
            -
                path: /dashboard
                backend:
                    serviceName: infrabox-static
                    servicePort: 80
            -
                path: /api/v1
                backend:
                    serviceName: infrabox-api
                    servicePort: 8080
            -
                path: /api/job
                backend:
                    serviceName: infrabox-api
                    servicePort: 8080
            {{ if .Values.github.enabled }}
            -
                path: /github/hook
                backend:
                    serviceName: infrabox-github-trigger
                    servicePort: 8080
            -
                path: /github/auth
                backend:
                    serviceName: infrabox-api
                    servicePort: 8080
            {{ end }}
            -
                path: /v2
                backend:
                    serviceName: infrabox-docker-registry
                    servicePort: 8080
            -
                path: /
                backend:
                    serviceName: infrabox-static
                    servicePort: 80
{{ if .Values.ingress.tls.enabled }}
    tls:
        - hosts:
            - {{ .Values.ingress.tls.host }}
          secretName: infrabox-tls-certs
{{ end }}
{{ end }}
