apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: infrabox-controller
    namespace: {{ default "infrabox-system" .Values.general.system_namespace }}
    labels:
        app: infrabox-controller
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: infrabox-controller
        spec:
            {{ if .Values.general.rbac.enabled }}
            serviceAccountName: infrabox-scheduler
            {{ end }}
            containers:
            -
                name: controller
                image: {{ required "general.docker_registry is required" .Values.general.docker_registry }}/{{ default "controller" .Values.controller.image }}:{{ required "controller.tag is required" .Values.controller.tag }}
                imagePullPolicy: Always
                env:
                {{ include "env_gerrit" . | indent 16 }}
                {{ include "env_local_cache" . | indent 16 }}
                {{ include "env_job" . | indent 16 }}
                {{ include "env_general" . | indent 16 }}
                {{ include "env_kubernetes" . | indent 16 }}
                -
                    name: INFRABOX_ROOT_URL
                    value: {{ required "root_url is required" .Values.root_url }}
                -
                    name: INFRABOX_SERVICE
                    value: {{ default "controller" .Values.controller.image }}
                -
                    name: INFRABOX_VERSION
                    value: {{ required "controller.tag is required" .Values.controller.tag }}
                volumeMounts:
                -
                    mountPath: /etc/docker
                    name: dockerd-config
                {{ include "mounts_rsa_private" . | indent 16 }}
            volumes:
                {{ include "volumes_rsa" . | indent 16 }}
                -
                    name: dockerd-config
                    configMap:
                        name: infrabox-dockerd-config
