apiVersion: core.infrabox.net/v1alpha1
kind: IBFunction
metadata:
    name: infrabox-default-function
spec:
    image: 192.168.1.31:5000/infrabox/job:latest
    securityContext:
        privileged: true
    resources:
        limits:
            cpu: 1000m
        requests:
            cpu: 1000m
            memory: 1Gi
    env:
    {{ include "env_general" . | indent 4 }}
    {{ include "env_job" . | indent 4 }}
    {{ include "env_gerrit" . | indent 4 }}
    -
        name: INFRABOX_LOCAL_CACHE_ENABLED
        value: {{ .Values.local_cache.enabled | quote }}
    -
        name: INFRABOX_SERVICE
        value: infrabox-default-function
    -
        name: INFRABOX_VERSION
        value: "unknown"
    volumeMounts:
    -
        mountPath: /etc/docker
        name: dockerd-config
    -
        name: data-dir
        mountPath: "/data"
{{ if .Values.local_cache.enabled }}
    -
        mountPath: /local-cache
        name: local-cache
{{ end }}
{{ if .Values.gerrit.enabled }}
    -
        mountPath: /tmp/gerrit
        name: gerrit-ssh
{{ end }}
    volumes:
    -
        name: data-dir
        emptyDir: {}
    -
        name: dockerd-config
        configMap:
            name: infrabox-dockerd-config
{{ if .Values.local_cache.enabled }}
    -
        name: local-cache
        hostPath:
            Path: {{ default "/tmp/infrabox/local_cache" .Values.local_cache.host_path }}
{{ end }}
{{ if .Values.gerrit.enabled }}
    -
        name: gerrit-ssh
        secret:
            secretName: infrabox-gerrit-ssh
{{ end }}
