apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "infrabox-service-gcp.fullname" . }}
  labels:
    app: {{ template "infrabox-service-gcp.name" . }}
    chart: {{ template "infrabox-service-gcp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "infrabox-service-garden.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "infrabox-service-garden.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: infrabox-service-garden
      containers:
        - name: {{ .Chart.Name }}
          command: ["./garden"]
          args: ["-gardenserviceaccount", "/var/run/infrabox.net/garden/service_account.json"]
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "Always"
          resources:
          volumeMounts:
          - name: service-account
            mountPath: "/var/run/infrabox.net/garden"
            readOnly: true
          env:
          - name: WATCH_NAMESPACE
            value: infrabox-worker
      volumes:
      - name: service-account
        secret:
          secretName: "infrabox-service-garden-sa"
