apiVersion: apps/v1
kind: Deployment
metadata:
  name: garden
spec:
  replicas: 1
  selector:
    matchLabels:
      name: garden
  template:
    metadata:
      labels:
        name: garden
    spec:
      containers:
        - name: garden
          image: 192.168.1.31:5000/infrabox/service-garden
          command:
          - garden
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
