{{ if .Values.docs.enabled }}
kind: Service
apiVersion: v1
metadata:
    name: infrabox-docs
    namespace: {{ default "infrabox-system" .Values.general.system_namespace }}
    labels:
        app: infrabox-docs
spec:
    selector:
        app: infrabox-docs
    ports:
    -
        name: http-web
        protocol: TCP
        port: 80
        targetPort: 80
{{ end }}
