imports:
- path: infrabox.jinja

resources:
- name: infrabox-cluster
  type: infrabox.jinja
  properties:
    zone: us-central1-a
    initialNodeCount: 3
    instanceType: n1-standard-2
    domainName: # REQUIRED: infrabox.example.com
    githubEnabled: true
    githubClientID: # REQUIRED: a client ID
    githubClientSecret: # REQUIRED: a secret ID
    githubLoginAllowedOrganizationsEnabled: false
    # githubLoginAllowedOrganizations: Org1,Org2
