kind: Service
apiVersion: v1
metadata:
    name: infrabox-static
    namespace: {{ template "system_namespace" . }}
    labels:
        app: infrabox-static
spec:
    selector:
        app: infrabox-static
    ports:
    -
        name: http-web
        protocol: TCP
        port: 80
        targetPort: 80
