apiVersion: gcp.service.infrabox.net/v1alpha1
kind: GKECluster
metadata:
  name: test-cluster-local
  labels:
    "service.infrabox.net/secret-name": "my-test-secret"
spec:
    #diskSize: "100"
    #machineType: "n1-standard-1"
    #enableNetworkPolicy: "false"
    numNodes: "1"
    #preemptible: "true"
    #enableAutoscaling: "false"
    #maxNodes: "1"
    #minNodes: "1"
