apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gkeclusters.gcp.service.infrabox.net
spec:
  group: gcp.service.infrabox.net
  version: v1alpha1
  names:
    kind: GKECluster
    plural: gkeclusters
  scope: Namespaced
