apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: operator
  template:
    metadata:
      labels:
        name: operator
    spec:
      containers:
        - name: operator
          image: 192.168.1.31:5000/infrabox/controller
          command:
          - operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
