{{ if .Values.api.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: infrabox-api
    namespace: {{ default "infrabox-system" .Values.general.system_namespace }}
    annotations:
        infrabox.net/checksum: {{ .Files.Get "values.yaml" | sha256sum }}
    labels:
        app: infrabox
        infrabox.net/component: api
spec:
    replicas: {{ default 1 .Values.api.replicas }}
    template:
        metadata:
            labels:
                app: infrabox
                infrabox.net/component: api
        spec:
            {{- if .Values.api.node_selector }}
            nodeSelector:
{{ toYaml .Values.api.node_selector | indent 16 }}
            {{- end }}
            containers:
            {{ include "containers_database" . | indent 12 }}
            {{ if .Values.gerrit.enabled }}
            -
                image: {{ .Values.general.docker_registry }}/{{ default "infrabox/gerrit/api" .Values.gerrit.api.image }}:{{ .Values.gerrit.api.tag }}
                imagePullPolicy: Always
                name: gerrit-api
                env:
                {{ include "env_general" . | indent 16 }}
                {{ include "env_gerrit" . | indent 16 }}
                -
                    name: INFRABOX_SERVICE
                    value: {{ default "infrabox/gerrit/api" .Values.gerrit.api.image }}
                -
                    name: INFRABOX_VERSION
                    value: {{ .Values.gerrit.api.tag }}
                volumeMounts:
                - name: gerrit-ssh
                  mountPath: /tmp/gerrit
                  readOnly: true
            {{ end }}
            {{ if .Values.github.enabled }}
            -
                image: {{ .Values.general.docker_registry }}/{{ default "infrabox/github/trigger" .Values.github.trigger.image }}:{{ .Values.github.trigger.tag }}
                imagePullPolicy: Always
                name: github-trigger
                env:
                {{ include "env_database" . | indent 16 }}
                {{ include "env_general" . | indent 16 }}
                {{ include "env_github_secrets" . | indent 16 }}
                -
                    name: INFRABOX_SERVICE
                    value: {{ default "infrabox/github/trigger" .Values.github.trigger.image }}
                -
                    name: INFRABOX_VERSION
                    value: {{ .Values.github.trigger.tag }}
            -
                image: {{ .Values.general.docker_registry }}/{{ default "infrabox/github/api" .Values.github.api.image }}:{{ .Values.github.api.tag }}
                imagePullPolicy: Always
                name: github-api
                env:
                {{ include "env_general" . | indent 16 }}
                {{ include "env_github" . | indent 16 }}
                -
                    name: INFRABOX_SERVICE
                    value: {{ default "infrabox/github/api" .Values.github.api.image }}
                -
                    name: INFRABOX_VERSION
                    value: {{ .Values.github.api.tag }}
            {{ end }}
            -
                name: api
                image: {{ .Values.general.docker_registry }}/{{ default "infrabox/api" .Values.api.image }}:{{ .Values.api.tag }}
                imagePullPolicy: Always
                command:
                - "node"
                - "/api/dist/server/app.js"
                volumeMounts:
                {{ if .Values.storage.gcs.enabled }}
                -
                    name: gcs-service-account
                    mountPath: /etc/infrabox/gcs
                    readOnly: true
                {{ end }}
                {{ if .Values.api.tls.enabled }}
                -
                    name: api-tls
                    mountPath: /var/run/infrabox
                    readOnly: true
                {{ end }}
                env:
                {{ include "env_database" . | indent 16 }}
                {{ include "env_gcs" . | indent 16 }}
                {{ include "env_s3" . | indent 16 }}
                {{ include "env_github" . | indent 16 }}
                {{ include "env_general" . | indent 16 }}
                -
                    name: INFRABOX_SERVICE
                    value: {{ default "infrabox/api" .Values.api.image }}
                -
                    name: INFRABOX_VERSION
                    value: {{ .Values.api.tag }}
                -
                    name: INFRABOX_API_LOG_CONSOLE
                    value: "true"
                -
                    name: INFRABOX_API_LOG_LEVEL
                    value: {{ default "info" .Values.api.log.level | quote }}
                -
                    name: INFRABOX_API_URL
                    value: {{ .Values.api.url }}
                -
                    name: INFRABOX_API_PORT
                    value: "8080"
                -
                    name: INFRABOX_API_TLS_ENABLED
                    value: {{ default "false" .Values.api.tls.enabled | quote }}
                -
                    name: INFRABOX_DOCKER_REGISTRY_URL
                    value: {{ .Values.docker_registry.url }}
                {{ if .Values.general.no_check_certificates }}
                -
                    name: NODE_TLS_REJECT_UNAUTHORIZED
                    value: "0"
                {{ end }}
            volumes:
                {{ include "volumes_database" . | indent 16 }}
                {{ if .Values.storage.gcs.enabled }}
                -
                    name: gcs-service-account
                    secret:
                        secretName: infrabox-gcs
                {{ end }}
                {{ if .Values.api.tls.enabled }}
                -
                    name: api-tls
                    secret:
                        secretName: infrabox-api-tls
                {{ end }}
                {{ if .Values.gerrit.enabled }}
                -
                    name: gerrit-ssh
                    secret:
                        secretName: infrabox-gerrit-ssh
                {{ end }}
{{ end }}
