{{ if .Values.api.enabled }}
kind: Service
apiVersion: v1
metadata:
    name: infrabox-api
    namespace: {{ default "infrabox-system" .Values.general.system_namespace }}
    labels:
        app: infrabox-api
        infrabox.net/component: api
spec:
    selector:
        app: infrabox-api
        infrabox.net/component: api
    type: NodePort
    ports:
    -
        name: http-web
        protocol: TCP
        port: 8080
        targetPort: 8080
{{ end }}
