apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ibfunctions.core.infrabox.net
spec:
  group: core.infrabox.net
  names:
    kind: IBFunction
    listKind: IBFunctionList
    plural: ibfunctions
    singular: ibfunction
  scope: Cluster
  version: v1alpha1
