apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ibfunctions.core.infrabox.net
spec:
  group: core.infrabox.net
  names:
    kind: IBFunction
    listKind: IBFunctionList
    plural: ibfunctions
    singular: ibfunction
  scope: Cluster
  version: v1alpha1
---
apiVersion: core.infrabox.net/v1alpha1
kind: IBFunction
metadata:
    name: infrabox-default-function
spec:
    image: 192.168.1.31:5000/infrabox/job:latest
    securityContext:
        privileged: true
    resources:
        limits:
            cpu: 1000m
        requests:
            cpu: 1000m
            memory: 1Gi
    env:
    {{ include "env_job" . | indent 4 }}
    {{ include "env_gerrit" . | indent 4 }}
    {{ include "env_general" . | indent 4 }}
    {{ include "env_local_cache" . | indent 4 }}
    -
        name: INFRABOX_SERVICE
        value: infrabox-default-function
    -
        name: INFRABOX_VERSION
        value: "unknown"
    volumeMounts:
    -
        mountPath: /etc/docker
        name: dockerd-config
    volumes:
    -
        name: dockerd-config
        configMap:
            name: infrabox-dockerd-config
